EVALUATE // 'Medidas'[$ Despesa Alelo]
SUMMARIZECOLUMNS(
	dimCLIENTES[COB_RAZAO_SOCIAL],
	"RANKING RECEITA", RANKX( ALL( dimCLIENTES[COB_RAZAO_SOCIAL] ) , CALCULATE( [$ Receita Bruta (FINAL)] ) ) ,
	"RECEITA BRUTA", [$ Receita Bruta (FINAL)]
	
) ORDER BY [RANKING RECEITA]